# Generated by Django 5.0.6 on 2026-02-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='category',
        ),
    ]
